### ISSUE TITLE
Dockerize the application

### ISSUE THREAD

**Issue by avinashupadhya99** [olavfosse/liracer#47]
**Is your feature request related to a problem? Please describe.**
Dockerizing the application makes it easier for other developers to set it up on their machines and also easier to deploy.

**Describe the solution you'd like**
The application should be dockerised for frontend and backend and a docker-compose file should be able to bring both of them up.

**Comment by avinashupadhya99** [comment]
Hey! I can do this if you want.

**Comment by olavfosse** [comment]
Hello. Thanks for the suggestion and offering to do it.

I do not want to dockerize the app since Docker is not supported on OpenBSD, FreeBSD and NetBSD. I might reconsider this if liracer's development environment becomes more complex, but for now setting it up is as simple as running `npm install` in the frontend and backend directory.
